const img = (path) => `https://picsum.photos/seed/${path}/500/750`;
const wide = (path) => `https://picsum.photos/seed/${path}/1280/720`;

export const CATALOG = [
  {
    title: 'Oppenheimer',
    year: 2023,
    genre: 'Drama',
    rating: 8.3,
    duration: '180 min',
    region: 'Hollywood',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Robert Downey Jr.'],
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    poster: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop: '/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
    trending: true
  },
  {
    title: 'Barbie',
    year: 2023,
    genre: 'Comedy',
    rating: 6.9,
    duration: '114 min',
    region: 'Hollywood',
    cast: ['Margot Robbie', 'Ryan Gosling', 'America Ferrera'],
    description: 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land.',
    poster: '/iuFNMS8U5cb6xfzi51Dbhv40mTM.jpg',
    backdrop: '/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg'
  },
  {
    title: 'Dune: Part Two',
    year: 2024,
    genre: 'Sci-Fi',
    rating: 8.5,
    duration: '166 min',
    region: 'Hollywood',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson'],
    description: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.',
    poster: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdrop: '/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
    trending: true
  },
  {
    title: 'Dune',
    year: 2021,
    genre: 'Sci-Fi',
    rating: 8.0,
    duration: '155 min',
    region: 'Hollywood',
    cast: ['Timothée Chalamet', 'Rebecca Ferguson', 'Oscar Isaac'],
    description: 'Paul Atreides travels to the most dangerous planet in the universe to ensure the future of his family and his people.',
    poster: '/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
    backdrop: '/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg'
  },
  {
    title: 'The Dark Knight',
    year: 2008,
    genre: 'Action',
    rating: 9.0,
    duration: '152 min',
    region: 'Hollywood',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    description: 'Batman faces the Joker, a criminal mastermind who plunges Gotham into anarchy.',
    poster: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop: '/nMKdUUepR0i5zn0y1T4CsSB5aR8.jpg',
    trending: true
  },
  {
    title: 'Inception',
    year: 2010,
    genre: 'Sci-Fi',
    rating: 8.8,
    duration: '148 min',
    region: 'Hollywood',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    description: 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.',
    poster: '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdrop: '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg'
  },
  {
    title: 'Interstellar',
    year: 2014,
    genre: 'Sci-Fi',
    rating: 8.7,
    duration: '169 min',
    region: 'Hollywood',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity’s survival.',
    poster: '/gEU2QniFSGqP4bRd6hgtcHBedyk.jpg',
    backdrop: '/xJHokMbljvjADYdit5fK5VQsXEG.jpg'
  },
  {
    title: 'Avengers: Endgame',
    year: 2019,
    genre: 'Action',
    rating: 8.4,
    duration: '181 min',
    region: 'Hollywood',
    cast: ['Robert Downey Jr.', 'Chris Evans', 'Scarlett Johansson'],
    description: 'The Avengers assemble once more to reverse Thanos’ actions and restore balance to the universe.',
    poster: '/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    backdrop: '/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg'
  },
  {
    title: 'Spider-Man: No Way Home',
    year: 2021,
    genre: 'Sci-Fi',
    rating: 8.2,
    duration: '148 min',
    region: 'Hollywood',
    cast: ['Tom Holland', 'Zendaya', 'Benedict Cumberbatch'],
    description: 'Peter Parker’s identity is revealed, and he asks Doctor Strange for help — opening the multiverse.',
    poster: '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
    backdrop: '/14QbnygCuTO0vl7CAFmPf1fgZfB.jpg',
    trending: true
  },
  {
    title: 'The Batman',
    year: 2022,
    genre: 'Action',
    rating: 7.8,
    duration: '176 min',
    region: 'Hollywood',
    cast: ['Robert Pattinson', 'Zoë Kravitz', 'Paul Dano'],
    description: 'Batman ventures into Gotham’s underworld when a sadistic killer leaves behind cryptic clues.',
    poster: '/74xTEgtARkkbNUqi4PURUKxR3Ll.jpg',
    backdrop: '/b0PlkZqsjfWONZ9FzMW4S8V1mCg.jpg'
  },
  {
    title: 'John Wick: Chapter 4',
    year: 2023,
    genre: 'Action',
    rating: 7.7,
    duration: '169 min',
    region: 'Hollywood',
    cast: ['Keanu Reeves', 'Donnie Yen', 'Bill Skarsgård'],
    description: 'John Wick uncovers a path to defeating the High Table — but before he can earn his freedom, he must face a new enemy.',
    poster: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    backdrop: '/h8gHn0OzBoaefsYseUByqsmEDMY.jpg',
    trending: true
  },
  {
    title: 'Top Gun: Maverick',
    year: 2022,
    genre: 'Action',
    rating: 8.2,
    duration: '131 min',
    region: 'Hollywood',
    cast: ['Tom Cruise', 'Miles Teller', 'Jennifer Connelly'],
    description: 'After thirty years, Maverick is still pushing the envelope as a top naval aviator.',
    poster: '/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
    backdrop: '/odJ4hx6g6vBt4lBWKFD1tI8W4Ly.jpg'
  },
  {
    title: 'Mad Max: Fury Road',
    year: 2015,
    genre: 'Action',
    rating: 8.1,
    duration: '120 min',
    region: 'Hollywood',
    cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'],
    description: 'In a post-apocalyptic wasteland, Max teams with Furiosa to flee from a tyrannical warlord.',
    poster: '/hA2ple9q4qnwxp3hKVNhroolsmu.jpg',
    backdrop: '/9eAn20UErb3paSZBe8rlmKz0pG2.jpg'
  },
  {
    title: 'Gladiator',
    year: 2000,
    genre: 'Action',
    rating: 8.5,
    duration: '155 min',
    region: 'Hollywood',
    cast: ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen'],
    description: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.',
    poster: '/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
    backdrop: '/5vzwP4kKJmXlYH4JKo0G0jYqJRq.jpg'
  },
  {
    title: 'Joker',
    year: 2019,
    genre: 'Drama',
    rating: 8.4,
    duration: '122 min',
    region: 'Hollywood',
    cast: ['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz'],
    description: 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society.',
    poster: '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    backdrop: '/n6bUcrOz5s6PvVxcFeTQ6S0fdBW.jpg'
  },
  {
    title: 'Parasite',
    year: 2019,
    genre: 'Drama',
    rating: 8.5,
    duration: '132 min',
    region: 'Korea',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'],
    description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    poster: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdrop: '/TU9NIjwzjoKPwQCzZg53nxUKkR.jpg'
  },
  {
    title: 'The Shawshank Redemption',
    year: 1994,
    genre: 'Drama',
    rating: 9.3,
    duration: '142 min',
    region: 'Hollywood',
    cast: ['Tim Robbins', 'Morgan Freeman'],
    description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    poster: '/q6y0Go1tsGEsmtFayUStH6BjmEI.jpg',
    backdrop: '/kXfqcdQKsA0UvsTQ1v4psedPAlI.jpg'
  },
  {
    title: 'Forrest Gump',
    year: 1994,
    genre: 'Drama',
    rating: 8.8,
    duration: '142 min',
    region: 'Hollywood',
    cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise'],
    description: 'The presidencies of Kennedy and Johnson, Vietnam, Watergate and more through the eyes of an Alabama man with a low IQ.',
    poster: '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    backdrop: '/qdIMHd4sEfJSckfVJfKQvisL02a.jpg'
  },
  {
    title: 'The Godfather',
    year: 1972,
    genre: 'Drama',
    rating: 9.2,
    duration: '175 min',
    region: 'Hollywood',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan'],
    description: 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.',
    poster: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdrop: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg'
  },
  {
    title: 'Whiplash',
    year: 2014,
    genre: 'Drama',
    rating: 8.5,
    duration: '107 min',
    region: 'Hollywood',
    cast: ['Miles Teller', 'J.K. Simmons'],
    description: 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing.',
    poster: '/7fnmW83s4KM2i2mXkMsxX6hQuLq.jpg',
    backdrop: '/fR0VZ0VE598zl1lrYf7IfBqEwQ2.jpg'
  },
  {
    title: 'Titanic',
    year: 1997,
    genre: 'Romance',
    rating: 7.9,
    duration: '194 min',
    region: 'Hollywood',
    cast: ['Leonardo DiCaprio', 'Kate Winslet'],
    description: 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
    poster: '/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
    backdrop: '/3W5vYQQnJQz1z3yQ0kQXoXqXqXq.jpg'
  },
  {
    title: 'La La Land',
    year: 2016,
    genre: 'Romance',
    rating: 8.0,
    duration: '128 min',
    region: 'Hollywood',
    cast: ['Ryan Gosling', 'Emma Stone'],
    description: 'A jazz pianist falls for an aspiring actress in Los Angeles.',
    poster: '/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
    backdrop: '/q7fXcrDPJcf6t3rzutaNwTzuKP1.jpg'
  },
  {
    title: 'The Notebook',
    year: 2004,
    genre: 'Romance',
    rating: 7.8,
    duration: '123 min',
    region: 'Hollywood',
    cast: ['Ryan Gosling', 'Rachel McAdams'],
    description: 'A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom.',
    poster: '/qom1SZSENdmHFNZBXbtJAU0PiKc.jpg',
    backdrop: '/jnsNQsNmfTG8HYgL7k4eH6q8k4F.jpg'
  },
  {
    title: 'Pride & Prejudice',
    year: 2005,
    genre: 'Romance',
    rating: 8.0,
    duration: '129 min',
    region: 'Hollywood',
    cast: ['Keira Knightley', 'Matthew Macfadyen'],
    description: 'Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy.',
    poster: '/sGjIvtVvTlWFwBxv8gSvnRH7aRv.jpg',
    backdrop: '/hH4YaZuH89H9zOQKKt7bzZXjJwC.jpg'
  },
  {
    title: 'Get Out',
    year: 2017,
    genre: 'Horror',
    rating: 7.8,
    duration: '104 min',
    region: 'Hollywood',
    cast: ['Daniel Kaluuya', 'Allison Williams'],
    description: 'A young African-American visits his white girlfriend’s parents for the weekend, where his simmering uneasiness becomes a nightmare.',
    poster: '/tFXcEccSQMf3lfhfIKnvgSwYcRy.jpg',
    backdrop: '/mZ4gEsKR7Pg3Z0r7A0pQeZ7YqXq.jpg'
  },
  {
    title: 'The Conjuring',
    year: 2013,
    genre: 'Horror',
    rating: 7.5,
    duration: '112 min',
    region: 'Hollywood',
    cast: ['Patrick Wilson', 'Vera Farmiga'],
    description: 'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence.',
    poster: '/wVYREutTvI2tmxr6ujrHT704wGF.jpg',
    backdrop: '/xu9zaAevzQ5nnrsXNViQB22gZpc.jpg'
  },
  {
    title: 'A Quiet Place',
    year: 2018,
    genre: 'Horror',
    rating: 7.5,
    duration: '90 min',
    region: 'Hollywood',
    cast: ['Emily Blunt', 'John Krasinski'],
    description: 'A family lives in silence while hiding from creatures that hunt by sound.',
    poster: '/nAU74GmpUk7t5iklEp3bufwDq4n.jpg',
    backdrop: '/a0u50nhM4YQ5vLFsZQmObB5X0X6.jpg'
  },
  {
    title: 'It',
    year: 2017,
    genre: 'Horror',
    rating: 7.3,
    duration: '135 min',
    region: 'Hollywood',
    cast: ['Bill Skarsgård', 'Jaeden Martell', 'Finn Wolfhard'],
    description: 'In the summer of 1989, a group of kids in Derry, Maine, band together to destroy a shape-shifting monster.',
    poster: '/9E2y5Q7WlNVNMlDN3a1qKqcr5gg.jpg',
    backdrop: '/tcheoA2nPATCm2vvXw2hVQoaEFD.jpg'
  },
  {
    title: 'Hereditary',
    year: 2018,
    genre: 'Horror',
    rating: 7.3,
    duration: '127 min',
    region: 'Hollywood',
    cast: ['Toni Collette', 'Alex Wolff', 'Milly Shapiro'],
    description: 'A grieving family is haunted by tragedy and disturbing secrets.',
    poster: '/p9fmuz2Oj3HtGBtS5KTFHJVQCgk.jpg',
    backdrop: '/4Q2NXc7gB8iUBy6dYqMsJ4YvHkx.jpg'
  },
  {
    title: 'RRR',
    year: 2022,
    genre: 'Indian',
    rating: 7.8,
    duration: '182 min',
    region: 'India',
    cast: ['N. T. Rama Rao Jr.', 'Ram Charan', 'Alia Bhatt'],
    description: 'A fictitious story about two legendary revolutionaries and their journey away from home before they started fighting for their country in the 1920s.',
    poster: '/wE0I6efQU4B1xTe5H3TeaHqSzvb.jpg',
    backdrop: '/1X7vow16X7CnSbiNQH8EWFb3d0S.jpg',
    trending: true
  },
  {
    title: 'Dangal',
    year: 2016,
    genre: 'Indian',
    rating: 8.3,
    duration: '161 min',
    region: 'India',
    cast: ['Aamir Khan', 'Fatima Sana Shaikh', 'Sanya Malhotra'],
    description: 'Former wrestler Mahavir Singh Phogat trains his daughters to become world-class wrestlers.',
    poster: '/pD2T4xPx80V9Ul5wDcJEvKh9I3Y.jpg',
    backdrop: '/7cNIriw9hOl6nAqcC4nZ2D1uU3A.jpg'
  },
  {
    title: '3 Idiots',
    year: 2009,
    genre: 'Indian',
    rating: 8.4,
    duration: '170 min',
    region: 'India',
    cast: ['Aamir Khan', 'R. Madhavan', 'Sharman Joshi'],
    description: 'Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently.',
    poster: '/66A9MqXOyVFCssoloscw68D0GAA.jpg',
    backdrop: '/u7kuUaySqXBVB50lU82R2xQWJ2.jpg'
  },
  {
    title: 'Jawan',
    year: 2023,
    genre: 'Indian',
    rating: 7.0,
    duration: '169 min',
    region: 'India',
    cast: ['Shah Rukh Khan', 'Nayanthara', 'Vijay Sethupathi'],
    description: 'A man is driven by a personal tragedy to go after the people who run a corrupt system.',
    poster: '/jFt1gS4x60XQjDEmKWwzqcYQJqB.jpg',
    backdrop: '/4XM8BULbq4o4S4pGhkJqKe0s6mO.jpg'
  },
  {
    title: 'Pathaan',
    year: 2023,
    genre: 'Indian',
    rating: 6.6,
    duration: '146 min',
    region: 'India',
    cast: ['Shah Rukh Khan', 'Deepika Padukone', 'John Abraham'],
    description: 'An Indian spy takes on a former soldier-turned-mercenary who has a vendetta against his homeland.',
    poster: '/kXFq4keJP2PfxaoeKysjJkeO9p.jpg',
    backdrop: '/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg'
  },
  {
    title: 'Baahubali: The Beginning',
    year: 2015,
    genre: 'Indian',
    rating: 8.0,
    duration: '159 min',
    region: 'India',
    cast: ['Prabhas', 'Rana Daggubati', 'Anushka Shetty'],
    description: 'In ancient India, an adventurous and daring man becomes involved in a decades-old feud between two warring peoples.',
    poster: '/9BAjt8nSSms62uOVYn1t3C3dVto.jpg',
    backdrop: '/uP5VSInPg7vvkBM4MxoK7zZmtOQ.jpg'
  },
  {
    title: 'PK',
    year: 2014,
    genre: 'Indian',
    rating: 8.1,
    duration: '153 min',
    region: 'India',
    cast: ['Aamir Khan', 'Anushka Sharma'],
    description: 'An alien on Earth loses the only device he can use to communicate with his spaceship. His innocent questions force the country to evaluate the impact of religion on its people.',
    poster: '/jz6n9S9xJ7Nfz0sCCeqLOdQbXCo.jpg',
    backdrop: '/kUAixhI0bYqfK0kV6j4W0P3oqgO.jpg'
  },
  {
    title: 'Spider-Man: Across the Spider-Verse',
    year: 2023,
    genre: 'Cartoon',
    rating: 8.6,
    duration: '140 min',
    region: 'Hollywood',
    cast: ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac'],
    description: 'Miles Morales catapults across the multiverse, where he meets a team of Spider-People charged with protecting its very existence.',
    poster: '/8Vt6mWEReuy4Of61Lnj5Xj704mT.jpg',
    backdrop: '/nGxUxi3PfXDRm7Vg95VBNgNM8yc.jpg',
    trending: true
  },
  {
    title: 'Spider-Man: Into the Spider-Verse',
    year: 2018,
    genre: 'Cartoon',
    rating: 8.4,
    duration: '117 min',
    region: 'Hollywood',
    cast: ['Shameik Moore', 'Jake Johnson', 'Hailee Steinfeld'],
    description: 'Teen Miles Morales becomes the Spider-Man of his universe and must join with five spider-powered individuals from other dimensions.',
    poster: '/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
    backdrop: '/7d6EY00g1c39SGZOoCJ5Py9nNth.jpg'
  },
  {
    title: 'Coco',
    year: 2017,
    genre: 'Cartoon',
    rating: 8.4,
    duration: '105 min',
    region: 'Hollywood',
    cast: ['Anthony Gonzalez', 'Gael García Bernal'],
    description: 'Aspiring musician Miguel, confronted with his family’s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather.',
    poster: '/gGEsBPAijhVUFoiNpgZXqZcdABh.jpg',
    backdrop: '/askg3SMvhqFI0ukUgWpbzo2kue7.jpg'
  },
  {
    title: 'Inside Out 2',
    year: 2024,
    genre: 'Cartoon',
    rating: 7.6,
    duration: '97 min',
    region: 'Hollywood',
    cast: ['Amy Poehler', 'Maya Hawke', 'Kensington Tallman'],
    description: 'Riley’s mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions.',
    poster: '/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
    backdrop: '/stKG2QcYHxJRgA0eTBEz6FrHXhh.jpg',
    trending: true
  },
  {
    title: 'The Lion King',
    year: 1994,
    genre: 'Cartoon',
    rating: 8.5,
    duration: '88 min',
    region: 'Hollywood',
    cast: ['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones'],
    description: 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
    poster: '/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg',
    backdrop: '/wXsB5FxN5XaIkKtA8KOSONw6ofg.jpg'
  },
  {
    title: 'Toy Story',
    year: 1995,
    genre: 'Cartoon',
    rating: 8.3,
    duration: '81 min',
    region: 'Hollywood',
    cast: ['Tom Hanks', 'Tim Allen'],
    description: 'A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy’s room.',
    poster: '/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg',
    backdrop: '/3Rfvhy1Nl6sSGJwyjb0QiZzZYlB.jpg'
  },
  {
    title: 'Zootopia',
    year: 2016,
    genre: 'Cartoon',
    rating: 8.0,
    duration: '108 min',
    region: 'Hollywood',
    cast: ['Ginnifer Goodwin', 'Jason Bateman'],
    description: 'In a city of anthropomorphic animals, a rookie bunny cop and a cynical con artist fox must work together to uncover a conspiracy.',
    poster: '/hlK0e0wAQ3VLuJcsfIYPvb4JVxi.jpg',
    backdrop: '/mhdeE1yReH1aVYYvSUvdRnMbKxq.jpg'
  },
  {
    title: 'The Matrix',
    year: 1999,
    genre: 'Sci-Fi',
    rating: 8.7,
    duration: '136 min',
    region: 'Hollywood',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    poster: '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdrop: '/l4QHerTSbMI7qgvasqxP0gI6ya4.jpg'
  },
  {
    title: 'Avatar',
    year: 2009,
    genre: 'Sci-Fi',
    rating: 7.9,
    duration: '162 min',
    region: 'Hollywood',
    cast: ['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver'],
    description: 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following orders and protecting an alien civilization.',
    poster: '/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg',
    backdrop: '/vL5LR6WdxWPjLPFRLe133jXAE6k.jpg'
  },
  {
    title: 'Everything Everywhere All at Once',
    year: 2022,
    genre: 'Sci-Fi',
    rating: 7.8,
    duration: '139 min',
    region: 'Hollywood',
    cast: ['Michelle Yeoh', 'Ke Huy Quan', 'Stephanie Hsu'],
    description: 'A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes.',
    poster: '/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg',
    backdrop: '/7ABsaBkO1jA2sujKy00oAzjfGAF.jpg'
  },
  {
    title: 'The Hangover',
    year: 2009,
    genre: 'Comedy',
    rating: 7.7,
    duration: '100 min',
    region: 'Hollywood',
    cast: ['Bradley Cooper', 'Ed Helms', 'Zach Galifianakis'],
    description: 'Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing.',
    poster: '/uluhlXubGu1VxU63X9VHCLWDAYM.jpg',
    backdrop: '/5aX0yI3lx0KKvdG3d7ZUdX3vQ5p.jpg'
  },
  {
    title: 'Superbad',
    year: 2007,
    genre: 'Comedy',
    rating: 7.6,
    duration: '113 min',
    region: 'Hollywood',
    cast: ['Jonah Hill', 'Michael Cera', 'Christopher Mintz-Plasse'],
    description: 'Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.',
    poster: '/ek8e8TXWF9mOvqhATbrS6PPcyUy.jpg',
    backdrop: '/qUq3UNdsd3J6fZ7tPGhVvyASxgM.jpg'
  },
  {
    title: 'Knives Out',
    year: 2019,
    genre: 'Comedy',
    rating: 7.9,
    duration: '130 min',
    region: 'Hollywood',
    cast: ['Daniel Craig', 'Ana de Armas', 'Chris Evans'],
    description: 'A detective investigates the death of a patriarch of an eccentric, combative family.',
    poster: '/pThyQovXQhfBUbuueA8fXd5nLfO.jpg',
    backdrop: '/4HWAQu28e2ya2rt3fBEq7HjJe8D.jpg'
  },
  {
    title: 'The Grand Budapest Hotel',
    year: 2014,
    genre: 'Comedy',
    rating: 8.1,
    duration: '99 min',
    region: 'Hollywood',
    cast: ['Ralph Fiennes', 'Tony Revolori', 'Saoirse Ronan'],
    description: 'A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy.',
    poster: '/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
    backdrop: '/nBjFQCiaCdAMf9bXWF0O9qvx2Zf.jpg'
  },
  {
    title: 'Pulp Fiction',
    year: 1994,
    genre: 'Others',
    rating: 8.9,
    duration: '154 min',
    region: 'Hollywood',
    cast: ['John Travolta', 'Samuel L. Jackson', 'Uma Thurman'],
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    poster: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdrop: '/suaEOtk1N1sgg2MTM7oZd2cfHQj.jpg'
  },
  {
    title: 'No Time to Die',
    year: 2021,
    genre: 'Action',
    rating: 7.3,
    duration: '163 min',
    region: 'Hollywood',
    cast: ['Daniel Craig', 'Léa Seydoux', 'Rami Malek'],
    description: 'James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help.',
    poster: '/iUgygt3YzqB35Si0iFykkZxk8rt.jpg',
    backdrop: '/r2GAjd4sROBW2J8N7EXVJId4Zey.jpg'
  },
  {
    title: 'Black Panther',
    year: 2018,
    genre: 'Action',
    rating: 7.3,
    duration: '134 min',
    region: 'Hollywood',
    cast: ['Chadwick Boseman', 'Michael B. Jordan', 'Lupita Nyong\'o'],
    description: 'T’Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future.',
    poster: '/uxzzxijgPIY7slzFvMotPv8wjKA.jpg',
    backdrop: '/b6ZJww1u3qHdwY3jFE0uUYxbF3B.jpg'
  },
  {
    title: 'Breaking Bad',
    year: 2008,
    genre: 'Drama',
    kind: 'season',
    count: 7,
    rating: 9.5,
    duration: '7 Episodes',
    region: 'USA',
    cast: ['Bryan Cranston', 'Aaron Paul', 'Anna Gunn'],
    description: 'A chemistry teacher diagnosed with cancer teams with a former student to secure his family’s future by manufacturing and selling methamphetamine.',
    poster: '/ztkUQFLlC19CCMYNH2FOxyM81KQ.jpg',
    backdrop: '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg'
  },
  {
    title: 'Stranger Things',
    year: 2016,
    genre: 'Sci-Fi',
    kind: 'season',
    count: 8,
    rating: 8.7,
    duration: '8 Episodes',
    region: 'USA',
    cast: ['Millie Bobby Brown', 'Finn Wolfhard', 'Winona Ryder'],
    description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
    poster: '/49WJjoVzDc7vMdr6WWjo5PyyOt9.jpg',
    backdrop: '/56v2KjBlU4XaOv9rVYEQypROD7P.jpg'
  },
  {
    title: 'Game of Thrones',
    year: 2011,
    genre: 'Drama',
    kind: 'season',
    count: 10,
    rating: 9.2,
    duration: '10 Episodes',
    region: 'USA',
    cast: ['Emilia Clarke', 'Kit Harington', 'Peter Dinklage'],
    description: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
    poster: '/1XS1oqL89opfnALlK2U8AXmF5gM.jpg',
    backdrop: '/2OMB0ynKlyIenMJWI2DsXbg7p50.jpg'
  },
  {
    title: 'The Last of Us',
    year: 2023,
    genre: 'Drama',
    kind: 'season',
    count: 9,
    rating: 8.7,
    duration: '9 Episodes',
    region: 'USA',
    cast: ['Pedro Pascal', 'Bella Ramsey'],
    description: 'After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity’s last hope.',
    poster: '/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg',
    backdrop: '/uDgy6hyPd82DG6X6ovatngyIJLz.jpg'
  },
  {
    title: 'Squid Game',
    year: 2021,
    genre: 'Drama',
    kind: 'season',
    count: 9,
    rating: 8.0,
    duration: '9 Episodes',
    region: 'Korea',
    cast: ['Lee Jung-jae', 'Park Hae-soo', 'HoYeon Jung'],
    description: 'Hundreds of cash-strapped players accept a strange invitation to compete in children’s games for a tempting prize — with deadly results.',
    poster: '/dDlEmu3EZ0Pgg93K2SVNLCjCBqE.jpg',
    backdrop: '/2EewmlD0vSZqjo7lHJ3k8wZJ1p6.jpg'
  },
  {
    title: 'Wednesday',
    year: 2022,
    genre: 'Comedy',
    kind: 'season',
    count: 8,
    rating: 8.1,
    duration: '8 Episodes',
    region: 'USA',
    cast: ['Jenna Ortega', 'Catherine Zeta-Jones'],
    description: 'Wednesday Addams is sent to Nevermore Academy, where she attempts to master her emerging psychic ability and solve a murder spree.',
    poster: '/9PFonBhy4cQy7Jz20NpMygcjOkZ.jpg',
    backdrop: '/iHSwvRVsRyxpX7FE7GbviaxvgGZ.jpg'
  },
  {
    title: 'The Mandalorian',
    year: 2019,
    genre: 'Sci-Fi',
    kind: 'season',
    count: 8,
    rating: 8.7,
    duration: '8 Episodes',
    region: 'USA',
    cast: ['Pedro Pascal', 'Grogu'],
    description: 'The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.',
    poster: '/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg',
    backdrop: '/9ijMGlJKqcslswWUzTEwScm82Gs.jpg'
  },
  {
    title: 'The Boys',
    year: 2019,
    genre: 'Action',
    kind: 'season',
    count: 8,
    rating: 8.7,
    duration: '8 Episodes',
    region: 'USA',
    cast: ['Karl Urban', 'Jack Quaid', 'Antony Starr'],
    description: 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.',
    poster: '/2zmTngn1tYC1FscpmYSML2ddByt.jpg',
    backdrop: '/mY7SeH4HFFxH1imYHI8LyKG5xZ.jpg'
  },
  {
    title: 'Money Heist',
    year: 2017,
    genre: 'Action',
    kind: 'season',
    count: 13,
    rating: 8.2,
    duration: '13 Episodes',
    region: 'Spain',
    cast: ['Úrsula Corberó', 'Álvaro Morte', 'Itziar Ituño'],
    description: 'An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history — stealing 2.4 billion euros from the Royal Mint of Spain.',
    poster: '/reEMJA1uz0CRv1cq99NLxONvCvZ.jpg',
    backdrop: '/xGexTKCJDkl12dTW4YCBDXWb1AD.jpg'
  },
  {
    title: 'Dark',
    year: 2017,
    genre: 'Sci-Fi',
    kind: 'season',
    count: 10,
    rating: 8.7,
    duration: '10 Episodes',
    region: 'Germany',
    cast: ['Louis Hofmann', 'Lisa Vicari', 'Maja Schöne'],
    description: 'A missing child sets four families on a frantic hunt for answers as they unearth a mind-bending mystery that spans three generations.',
    poster: '/apbrbWs8M9lyOpJYU5WXrpFcx1z.jpg',
    backdrop: '/5LoXFBRnIu9pCOlUyudaDsbk8hF.jpg'
  },
  {
    title: 'The Witcher',
    year: 2019,
    genre: 'Action',
    kind: 'season',
    count: 8,
    rating: 8.0,
    duration: '8 Episodes',
    region: 'USA',
    cast: ['Henry Cavill', 'Anya Chalotra', 'Freya Allan'],
    description: 'Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.',
    poster: '/7vjaCdMw15FEbXy2Gym5YKH32R.jpg',
    backdrop: '/jBJWaqoSCiARWtfV0FlqR8BLvLf.jpg'
  },
  {
    title: 'Succession',
    year: 2018,
    genre: 'Drama',
    kind: 'season',
    count: 10,
    rating: 8.8,
    duration: '10 Episodes',
    region: 'USA',
    cast: ['Brian Cox', 'Jeremy Strong', 'Sarah Snook'],
    description: 'The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their father finds himself declining in health.',
    poster: '/7HWTnjgNzh7JzF3pC5Wbg2RWqNE.jpg',
    backdrop: '/6USbtjzZydH8vZbqIqzU2fZ5n8K.jpg'
  },
  {
    title: 'The Bear',
    year: 2022,
    genre: 'Comedy',
    kind: 'season',
    count: 8,
    rating: 8.6,
    duration: '8 Episodes',
    region: 'USA',
    cast: ['Jeremy Allen White', 'Ebon Moss-Bachrach', 'Ayo Edebiri'],
    description: 'A young chef from the fine dining world returns to Chicago to run his family’s sandwich shop.',
    poster: '/sHFl4RZbMlyH1Q1oF09U3yBLNAU.jpg',
    backdrop: '/9zcbqSxfrTaPPRlIH1Fq08ooLPD.jpg'
  },
  {
    title: 'Shōgun',
    year: 2024,
    genre: 'Drama',
    kind: 'season',
    count: 10,
    rating: 8.7,
    duration: '10 Episodes',
    region: 'USA',
    cast: ['Hiroyuki Sanada', 'Cosmo Jarvis', 'Anna Sawai'],
    description: 'When a mysterious European ship is found marooned in a nearby fishing village, Lord Yoshii Toranaga discovers secrets that could tip the scales of power.',
    poster: '/7O4iVfOMQmdCSxhOg1WnzF1T45p.jpg',
    backdrop: '/6YwkGolwdOMNpbTOmLjoehlBWsT.jpg',
    trending: true
  },
  {
    title: 'The Office',
    year: 2005,
    genre: 'Comedy',
    kind: 'season',
    count: 6,
    rating: 9.0,
    duration: '6 Episodes',
    region: 'USA',
    cast: ['Steve Carell', 'Rainn Wilson', 'John Krasinski'],
    description: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.',
    poster: '/qWnJzyZhyy74gka5yKlU15lO7te.jpg',
    backdrop: '/m3tdSnCB5WjDDQdlkDwwNDfiT0k.jpg'
  },
  {
    title: 'Sherlock',
    year: 2010,
    genre: 'Drama',
    kind: 'season',
    count: 3,
    rating: 9.1,
    duration: '3 Episodes',
    region: 'UK',
    cast: ['Benedict Cumberbatch', 'Martin Freeman'],
    description: 'A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.',
    poster: '/7WTsnHkb6b3HbO4Qa2BhAlvcxOG.jpg',
    backdrop: '/bOjUPNy5YIuGna0cJOQOTz4yKgQ.jpg'
  },
  {
    title: 'The Conjuring 2',
    year: 2016,
    genre: 'Horror',
    rating: 7.3,
    duration: '134 min',
    region: 'Hollywood',
    cast: ['Patrick Wilson', 'Vera Farmiga', 'Madison Wolfe'],
    description: 'Ed and Lorraine Warren travel to London to help a single mother raising four children alone in a haunted house.',
    poster: '/z7ALH8OOi8sPwLYs1RfJ1d1hCZd.jpg',
    backdrop: '/k1PKfSMvnNT4dDlMabEo1o2qN8.jpg'
  },
  {
    title: 'The Exorcist',
    year: 1973,
    genre: 'Horror',
    rating: 8.1,
    duration: '122 min',
    region: 'Hollywood',
    cast: ['Ellen Burstyn', 'Max von Sydow', 'Linda Blair'],
    description: 'When a young girl becomes possessed, her mother seeks the help of two priests to save her.',
    poster: '/4ucLGcXVVSVnsfkGtbLY4XAius8.jpg',
    backdrop: '/o0s4XsEDfDlvitNpA61qEJXUqP.jpg'
  },
  {
    title: 'Scream',
    year: 1996,
    genre: 'Horror',
    rating: 7.4,
    duration: '111 min',
    region: 'Hollywood',
    cast: ['Neve Campbell', 'Courteney Cox', 'David Arquette'],
    description: 'A year after the murder of her mother, a teenage girl is terrorized by a new killer, who targets the girl and her friends.',
    poster: '/3O5_0dxJHrdnZlUQDS4LOPXoQEs.jpg',
    backdrop: '/7uFkF8j40t3k3bL1jNqB4y3T3jE.jpg'
  },
  {
    title: 'Halloween',
    year: 1978,
    genre: 'Horror',
    rating: 7.7,
    duration: '91 min',
    region: 'Hollywood',
    cast: ['Jamie Lee Curtis', 'Donald Pleasence'],
    description: 'Fifteen years after murdering his sister on Halloween night, Michael Myers escapes from a psychiatric hospital and returns to his hometown.',
    poster: '/q3c9XEKtx1qvr6T4d2OyJd1fwPz.jpg',
    backdrop: '/bvfYKKL1Gfz5KJw2a6x6Z9F3Mmk.jpg'
  },
  {
    title: 'Pirates of the Caribbean',
    year: 2003,
    genre: 'Action',
    rating: 8.0,
    duration: '143 min',
    region: 'Hollywood',
    cast: ['Johnny Depp', 'Orlando Bloom', 'Keira Knightley'],
    description: 'A swashbuckling epic adventure featuring a roguish buccaneer and his quest for a legendary treasure.',
    poster: '/z8onk7LV9Mmw6zKz4hT6pzQ0TJs.jpg',
    backdrop: '/2dmeLxdYb6JXjXfGs4G32O40v9Z.jpg'
  },
  {
    title: 'The Lord of the Rings: The Return of the King',
    year: 2003,
    genre: 'Action',
    rating: 8.9,
    duration: '201 min',
    region: 'Hollywood',
    cast: ['Elijah Wood', 'Viggo Mortensen', 'Ian McKellen'],
    description: 'Gandalf and Aragorn lead the World of Men against Sauron\'s army to draw his gaze from Frodo and Sam as they approach Mount Doom.',
    poster: '/rCzpDGLbOoPwLjy7OYinsLVBzrq.jpg',
    backdrop: '/pm0RiwNpSja8gR0BTWpxo5a9Bbl.jpg'
  },
  {
    title: 'Kill Bill: Volume 1',
    year: 2003,
    genre: 'Action',
    rating: 8.1,
    duration: '111 min',
    region: 'Hollywood',
    cast: ['Uma Thurman', 'Lucy Liu', 'Vivica A. Fox'],
    description: 'After awakening from a four-year coma, a former assassin wreaks vengeance on the team who betrayed her.',
    poster: '/v7z3KwRJqKJ0k7l4Jj0H2XGZ1g3.jpg',
    backdrop: '/jI3fYx9v1X3V8sEa0b6F2XcY0dD.jpg'
  },
  {
    title: 'Casino Royale',
    year: 2006,
    genre: 'Action',
    rating: 8.0,
    duration: '144 min',
    region: 'Hollywood',
    cast: ['Daniel Craig', 'Eva Green', 'Mads Mikkelsen'],
    description: 'James Bond earns his license to kill and faces a ruthless banker who funds terrorists in a high-stakes poker game.',
    poster: '/n3pIoSnqfEgfb8fDcOMgBmDOlA.jpg',
    backdrop: '/zGC1XqfS0c0S3x0Tq5d3V9F0f2D.jpg'
  },
  {
    title: 'Wonder Woman',
    year: 2017,
    genre: 'Action',
    rating: 7.4,
    duration: '141 min',
    region: 'Hollywood',
    cast: ['Gal Gadot', 'Chris Pine', 'Robin Wright'],
    description: 'When an American pilot crashes on Themyscira and tells of a massive conflict raging in the outside world, Diana leaves her home to end the threat.',
    poster: '/gXLz1wGMR2MdYOPPIKLbwWRm1vx.jpg',
    backdrop: '/pF7tWJWnHRO4BIPQ1wFGvl7lXKf.jpg'
  },
  {
    title: 'Jurassic Park',
    year: 1993,
    genre: 'Sci-Fi',
    rating: 8.2,
    duration: '127 min',
    region: 'Hollywood',
    cast: ['Sam Neill', 'Laura Dern', 'Jeff Goldblum'],
    description: 'A pragmatic paleontologist touring a mostly completed theme park on an island is tasked with protecting children after the power goes out.',
    poster: '/iuFNMS8U5cb6xfzi51Dbhv40mTM.jpg',
    backdrop: '/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg'
  },
  {
    title: 'E.T. the Extra-Terrestrial',
    year: 1982,
    genre: 'Sci-Fi',
    rating: 7.9,
    duration: '115 min',
    region: 'Hollywood',
    cast: ['Henry Thomas', 'Drew Barrymore', 'Robert MacNaughton'],
    description: 'A troubled child summons the courage to help a friendly alien escape Earth and return to his home world.',
    poster: '/an0nD6ouqffO46NkGvMiLDJwYri.jpg',
    backdrop: '/oIciQWr8Vwv0RDqqa3fC1L1wjvG.jpg'
  },
  {
    title: 'Blade Runner 2049',
    year: 2017,
    genre: 'Sci-Fi',
    rating: 8.0,
    duration: '164 min',
    region: 'Hollywood',
    cast: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas'],
    description: 'Young Blade Runner K\'s discovery of a long-buried secret leads him on a quest to find a former Blade Runner who\'s been missing for 30 years.',
    poster: '/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    backdrop: '/sAtoM32u2nVuFJm8e4gEs5kE4eS.jpg'
  },
  {
    title: 'Back to the Future',
    year: 1985,
    genre: 'Sci-Fi',
    rating: 8.5,
    duration: '116 min',
    region: 'Hollywood',
    cast: ['Michael J. Fox', 'Christopher Lloyd', 'Lea Thompson'],
    description: 'Marty McFly, a teenager, is accidentally sent thirty years into the past in a time-traveling DeLorean built by his eccentric scientist friend.',
    poster: '/fNOH9fCp6NJQJt3Hf3C6mMFPLpP.jpg',
    backdrop: '/p0F6sMQuliQgOOgimjsEzKiNYxo.jpg'
  },
  {
    title: 'The Lion King',
    year: 2019,
    genre: 'Cartoon',
    rating: 6.8,
    duration: '118 min',
    region: 'Hollywood',
    cast: ['Donald Glover', 'Beyoncé', 'James Earl Jones'],
    description: 'After the murder of his father, a young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.',
    poster: '/sIVtTHqbSp22PUGKq2MC3kAD2bP.jpg',
    backdrop: '/wXsB5FxN5XaIkKtA8KOSONw6ofg.jpg'
  },
  {
    title: 'Frozen',
    year: 2013,
    genre: 'Cartoon',
    rating: 7.4,
    duration: '102 min',
    region: 'Hollywood',
    cast: ['Idina Menzel', 'Kristen Bell', 'Jonathan Groff'],
    description: 'When the newly crowned Queen Elsa accidentally uses her power to turn things into ice, her sister Anna teams up with a mountain man to save the kingdom.',
    poster: '/pjeMs3yqRmFL3giJy0PMmu6EHTn.jpg',
    backdrop: '/xJWPZIYOEFIjZpBL7SVBGnzRYXp.jpg'
  },
  {
    title: 'Moana',
    year: 2016,
    genre: 'Cartoon',
    rating: 7.6,
    duration: '107 min',
    region: 'Hollywood',
    cast: ['Auli\'i Cravalho', 'Dwayne Johnson'],
    description: 'In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches Moana\'s island, she answers the Ocean\'s call to seek out Maui.',
    poster: '/wXdyJ0XlpFbJ8PYyp2bMFz0X0Nq.jpg',
    backdrop: '/tKDfWdXF4l7cRSHsdv2UwxV5D1w.jpg'
  },
  {
    title: 'Avatar: The Way of Water',
    year: 2022,
    genre: 'Sci-Fi',
    rating: 7.6,
    duration: '192 min',
    region: 'Hollywood',
    cast: ['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver'],
    description: 'Jake Sully and Neytiri form a family and do everything they can to stay together, but when old threats return, they must leave their home.',
    poster: '/t6HIqrRLclmCA50ErU1K7N7M0Hz.jpg',
    backdrop: '/149BUz7jzjNYypJqN40ML07P7hv.jpg'
  },
  {
    title: 'The Hunger Games',
    year: 2012,
    genre: 'Action',
    rating: 7.2,
    duration: '142 min',
    region: 'Hollywood',
    cast: ['Jennifer Lawrence', 'Josh Hutcherson', 'Liam Hemsworth'],
    description: 'In a dark vision of the near future, a young girl is selected to participate in a compulsory televised fight to the death.',
    poster: '/yXCbLVDY3e0TTBqoS3zSRRBx8f4.jpg',
    backdrop: '/gKIhO4Cg3pKawapgGSGvJMX8wFH.jpg'
  },
  {
    title: 'Catch Me If You Can',
    year: 2002,
    genre: 'Others',
    rating: 8.1,
    duration: '141 min',
    region: 'Hollywood',
    cast: ['Leonardo DiCaprio', 'Tom Hanks', 'Christopher Walken'],
    description: 'The true story of Frank Abagnale Jr., a brilliant young con man who impersonated a pilot, doctor, and lawyer before his 19th birthday.',
    poster: '/lsMyGkLuKRdB87cKCjZdOeVlCCE.jpg',
    backdrop: '/6vJ2PqaaiKfMIEB6hJc3YkXpXpB.jpg'
  },
  {
    title: 'The Departed',
    year: 2006,
    genre: 'Drama',
    rating: 8.5,
    duration: '151 min',
    region: 'Hollywood',
    cast: ['Leonardo DiCaprio', 'Matt Damon', 'Jack Nicholson'],
    description: 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
    poster: '/fIRgVmHrb7e38eKBp8Dy0i3aXHQ.jpg',
    backdrop: '/jYFGDHYRPF3Ue0hKE813WwbGkqA.jpg'
  },
  {
    title: 'The Prestige',
    year: 2006,
    genre: 'Sci-Fi',
    rating: 8.5,
    duration: '130 min',
    region: 'Hollywood',
    cast: ['Christian Bale', 'Hugh Jackman', 'Scarlett Johansson'],
    description: 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have.',
    poster: '/bdN3gXuIZYaJP7ftKK2sU0nPtEA.jpg',
    backdrop: '/pTDUMqD1b7F34fJcbfPNF0lh7jJ.jpg'
  },
  {
    title: 'Goodfellas',
    year: 1990,
    genre: 'Drama',
    rating: 8.7,
    duration: '146 min',
    region: 'Hollywood',
    cast: ['Ray Liotta', 'Robert De Niro', 'Joe Pesci'],
    description: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife and his mob partners.',
    poster: '/aKuNiUjfDkN8avcZz4o5aaSRhQO.jpg',
    backdrop: '/gMVMAuJJM8pLhBsT2kF7Kx9KI6F.jpg'
  },
  {
    title: 'Se7en',
    year: 1995,
    genre: 'Others',
    rating: 8.6,
    duration: '127 min',
    region: 'Hollywood',
    cast: ['Brad Pitt', 'Morgan Freeman', 'Kevin Spacey'],
    description: 'Two detectives hunt a serial killer who uses the seven deadly sins as his motives.',
    poster: '/6yoghtyTpznpBik8EngEmJskVUO.jpg',
    backdrop: '/z6mfmSMuEAMTkEJf5AvN7bP2jXM.jpg'
  },
  {
    title: 'Fight Club',
    year: 1999,
    genre: 'Others',
    rating: 8.8,
    duration: '139 min',
    region: 'Hollywood',
    cast: ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'],
    description: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
    poster: '/pB8BM7pdSp6B6Ih7QI4S2t0POoT.jpg',
    backdrop: '/hZkgoQYus5dXo3H8T7CYV25UmID.jpg'
  },
  {
    title: 'The Green Mile',
    year: 1999,
    genre: 'Drama',
    rating: 8.6,
    duration: '189 min',
    region: 'Hollywood',
    cast: ['Tom Hanks', 'Michael Clarke Duncan'],
    description: 'The lives of guards on Death Row are affected by one of their charges: a gentle giant with a mysterious gift.',
    poster: '/velWPhVMQdQK3hIkRO4Rin7aH5X.jpg',
    backdrop: '/kXkGij2ZP3UG2x3GZLmlaXzLRjE.jpg'
  },
  {
    title: 'Apocalypto',
    year: 2006,
    genre: 'Action',
    rating: 7.8,
    duration: '139 min',
    region: 'Hollywood',
    cast: ['Rudy Youngblood', 'Raoul Trujillo'],
    description: 'As the Mayan civilization faces decline, a young man is taken on a perilous journey to the heart of a great city.',
    poster: '/hGGAvVHfJRqRh7V4WcNax9JzKEp.jpg',
    backdrop: '/qV4wr1ySJp73xNMDL3Rf5i3p3nC.jpg'
  },
  {
    title: 'District 9',
    year: 2009,
    genre: 'Sci-Fi',
    rating: 7.9,
    duration: '112 min',
    region: 'International',
    cast: ['Sharlto Copley', 'David James'],
    description: 'An alien species is stranded in South Africa and forced to live in a slum, while a bureaucrat is exposed to their secret biology.',
    poster: '/lo1VBIPu0kN1pRk5Cw4N2n1xXqj.jpg',
    backdrop: '/4Pwyv8T3wU7KJ9b6tW3f1zFk0qN.jpg'
  },
  {
    title: 'Crouching Tiger, Hidden Dragon',
    year: 2000,
    genre: 'Action',
    rating: 7.7,
    duration: '120 min',
    region: 'China',
    cast: ['Chow Yun-Fat', 'Michelle Yeoh', 'Zhang Ziyi'],
    description: 'Two warriors in pursuit of a stolen sword and a notorious fugitive are led to an impressionable young martial artist.',
    poster: '/iND1MbIGsQ1VRq6sCw8TuU8Jxvp.jpg',
    backdrop: '/dHfFz0d5x2q0p9R3z3x1Z9Fk9rA.jpg'
  },
  {
    title: 'Life Is Beautiful',
    year: 1997,
    genre: 'Drama',
    rating: 8.6,
    duration: '116 min',
    region: 'Italy',
    cast: ['Roberto Benigni', 'Nicoletta Braschi'],
    description: 'When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor, and imagination to protect his son.',
    poster: '/7DyLjUx2m4eUYVhPx4s98RnPNlb.jpg',
    backdrop: '/4FBbLkFsOxgLMQo5f1njp1ZfBfG.jpg'
  },
  {
    title: 'The Pianist',
    year: 2002,
    genre: 'Drama',
    rating: 8.5,
    duration: '150 min',
    region: 'Hollywood',
    cast: ['Adrien Brody', 'Thomas Kretschmann'],
    description: 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.',
    poster: '/jHxqCwbEU46W1x9sB1GoDr13dWB.jpg',
    backdrop: '/mZVF6lq4gF0E3i4fR2qY0GqO3sH.jpg'
  },
  {
    title: 'Amélie',
    year: 2001,
    genre: 'Comedy',
    rating: 8.3,
    duration: '122 min',
    region: 'France',
    cast: ['Audrey Tautou', 'Mathieu Kassovitz'],
    description: 'Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and discovers love along the way.',
    poster: '/0zR2o2phA0hOd2oB03p2DnEC1aF.jpg',
    backdrop: '/oPvo4aJPYiFJg1H4C5R9fC7pxBE.jpg'
  },
  {
    title: 'In the Mood for Love',
    year: 2000,
    genre: 'Romance',
    rating: 8.1,
    duration: '98 min',
    region: 'Hong Kong',
    cast: ['Tony Leung', 'Maggie Cheung'],
    description: 'Two neighbors form a strong bond after both suspect their spouses of infidelity, but agree to keep their relationship platonic.',
    poster: '/iYypPT4bhqXfq1b6EnmxkWdnICM.jpg',
    backdrop: '/uQ8nCEHkfT0G31cEyT0p5hIc3Cx.jpg'
  },
  {
    title: 'Oldboy',
    year: 2003,
    genre: 'Others',
    rating: 8.4,
    duration: '120 min',
    region: 'Korea',
    cast: ['Choi Min-sik', 'Yoo Ji-tae', 'Kang Hye-jung'],
    description: 'After being imprisoned for 15 years, a man is released and sets out to find the person who imprisoned him and the reason why.',
    poster: '/iX93vcjOLcJz8LPEyBFkRA0TUwH.jpg',
    backdrop: '/jA3b0zIvJ2dY3w1jE6R3D2qj3iS.jpg'
  },
  {
    title: 'Train to Busan',
    year: 2016,
    genre: 'Horror',
    rating: 7.8,
    duration: '118 min',
    region: 'Korea',
    cast: ['Gong Yoo', 'Jung Yu-mi', 'Ma Dong-seok'],
    description: 'Martial law is declared when a mysterious viral outbreak pushes Korea into a state of emergency. Those on an express train to Busan must fight for survival.',
    poster: '/qWEGs9luqc6UBS4vd3xJ609iImk.jpg',
    backdrop: '/kX2nD3Fq3d8jH9bT6v5pY5nX2rA.jpg'
  },
  {
    title: 'City of God',
    year: 2002,
    genre: 'Drama',
    rating: 8.6,
    duration: '130 min',
    region: 'Brazil',
    cast: ['Alexandre Rodrigues', 'Leandro Firmino'],
    description: 'In the slums of Rio, two kids paths diverge; one becomes a photographer, the other a drug dealer.',
    poster: '/k7eYdWUYZQ90C3d4bk1B0dO0z1r.jpg',
    backdrop: '/jG1gJfKJ7WJVNbPHh8z0aPpGg2A.jpg'
  },
  {
    title: 'Pan\'s Labyrinth',
    year: 2006,
    genre: 'Others',
    rating: 8.2,
    duration: '118 min',
    region: 'Spain',
    cast: ['Ivana Baquero', 'Sergi López', 'Maribel Verdú'],
    description: 'In the Falangist Spain of 1944, a girl escapes into an eerie but captivating fantasy world.',
    poster: '/3GpQkE03E9S2b76Xw8QH0jF1FkM.jpg',
    backdrop: '/pFt12dH3KJmB3gKj2C5dQ3Z7Z2E.jpg'
  },
  {
    title: 'Rang De Basanti',
    year: 2006,
    genre: 'Indian',
    rating: 8.2,
    duration: '167 min',
    region: 'India',
    cast: ['Aamir Khan', 'Soha Ali Khan', 'Siddharth'],
    description: 'A British filmmaker comes to India to make a film about Indian revolutionaries. Her students are inspired to become modern-day freedom fighters.',
    poster: '/5x5j8QbLPoI2jn8pKkGR6z4FnGM.jpg',
    backdrop: '/rH2bHdGk1p8V4z3s3FvYf7q4eY6.jpg'
  },
  {
    title: 'Lagaan',
    year: 2001,
    genre: 'Indian',
    rating: 8.1,
    duration: '224 min',
    region: 'India',
    cast: ['Aamir Khan', 'Gracy Singh'],
    description: 'The people of a small village in Victorian India stake their future on a game of cricket against their cruel British rulers.',
    poster: '/eLq4R7b1X6B8y9f3pCn0V0d8dAf.jpg',
    backdrop: '/f3xYpK5qM2g2nJ9J3V8VwZkD7dE.jpg'
  },
  {
    title: 'Drishyam',
    year: 2013,
    genre: 'Drama',
    rating: 8.3,
    duration: '160 min',
    region: 'India',
    cast: ['Mohanlal', 'Meena', 'Ashwathy'],
    description: 'A man goes to great lengths to cover up a murder committed by his family and protect them from the law.',
    poster: '/qG6Yf9a9vV3p5p2Q8lZ8W2cD2rA.jpg',
    backdrop: '/n3kP2bO6c6s1z1V8C5k6Y4w7dF9.jpg'
  },
  {
    title: 'Gangs of Wasseypur',
    year: 2012,
    genre: 'Action',
    rating: 8.2,
    duration: '178 min',
    region: 'India',
    cast: ['Manoj Bajpayee', 'Nawazuddin Siddiqui', 'Richa Chadha'],
    description: 'A coal mafia family is locked in a decades-long blood feud with another family in the Indian heartland.',
    poster: '/r9d3Xj2p8V7V3k3p8v6Y4w5z1dE.jpg',
    backdrop: '/z9k5Q3b2X9q3k3p8v6Y4w5z1dE.jpg'
  },
  {
    title: 'Spirited Away',
    year: 2001,
    genre: 'Cartoon',
    rating: 8.6,
    duration: '125 min',
    region: 'Japan',
    cast: ['Rumi Hiiragi', 'Miyu Irino'],
    description: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.',
    poster: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdrop: '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg'
  },
  {
    title: 'Your Name',
    year: 2016,
    genre: 'Cartoon',
    rating: 8.4,
    duration: '106 min',
    region: 'Japan',
    cast: ['Ryunosuke Kamiki', 'Mone Kamishiraishi'],
    description: 'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?',
    poster: '/q719jXXEzOoYaps6babgKnONONX.jpg',
    backdrop: '/dIWwZWReH0dfR8x88v5sU3siQel.jpg'
  },
  {
    title: 'Princess Mononoke',
    year: 1997,
    genre: 'Cartoon',
    rating: 8.4,
    duration: '134 min',
    region: 'Japan',
    cast: ['Yoji Matsuda', 'Yuriko Ishida', 'Akihiro Miwa'],
    description: 'On a journey to find the cure for a Tatarigami curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony.',
    poster: '/jHWmNr7m544fJ8eItsfN4f5OFsG.jpg',
    backdrop: '/7czjm2bK3J1M1MpGMIHJ8dN1wPe.jpg'
  },
  {
    title: 'Grave of the Fireflies',
    year: 1988,
    genre: 'Cartoon',
    rating: 8.5,
    duration: '89 min',
    region: 'Japan',
    cast: ['Tsutomu Tatsumi', 'Ayano Shiraishi'],
    description: 'A young boy and his little sister struggle to survive in Japan during World War II.',
    poster: '/qG38jT3R8qF6P2dG5D2z3s1r0vA.jpg',
    backdrop: '/q6y0Go1tsGEsmtFayUStH6BjmEI.jpg'
  },
  {
    title: 'Chernobyl',
    year: 2019,
    genre: 'Drama',
    kind: 'season',
    count: 5,
    rating: 9.4,
    duration: '5 Episodes',
    region: 'USA',
    cast: ['Jared Harris', 'Stellan Skarsgård', 'Emily Watson'],
    description: 'In April 1986, the city of Chernobyl in the Soviet Union suffers one of the worst nuclear disasters in history.',
    poster: '/hlLXt2tOPT6RRnjiUmoxyG1LTFX.jpg',
    backdrop: '/p1L0ax6NAWn3j7CYH2fb1f9T9zJ.jpg'
  },
  {
    title: 'Peaky Blinders',
    year: 2013,
    genre: 'Drama',
    kind: 'season',
    count: 6,
    rating: 8.8,
    duration: '6 Episodes',
    region: 'UK',
    cast: ['Cillian Murphy', 'Helen McCrory', 'Paul Anderson'],
    description: 'A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps.',
    poster: '/vUUqO2V2d1waFEP7G2wPwFqX45j.jpg',
    backdrop: '/wiE9doxiLwq3WCGamDIOb2PqBqc.jpg'
  },
  {
    title: 'Arcane',
    year: 2021,
    genre: 'Action',
    kind: 'season',
    count: 9,
    rating: 9.0,
    duration: '9 Episodes',
    region: 'USA',
    cast: ['Hailee Steinfeld', 'Ella Purnell', 'Kevin Alejandro'],
    description: 'Set in Riot Games\' utopian region of Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League of Legends champions.',
    poster: '/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg',
    backdrop: '/rkB4LyC3mWfbSMIXBQGzL2Lbo2p.jpg'
  }
].map((item) => ({
  ...item,
  imageUrl: img(item.poster),
  backdropUrl: wide(item.backdrop || item.poster)
}));

export const ROW_TITLES = {
  recent: [
    'Inside Out 2',
    'Dune: Part Two',
    'Shōgun',
    'Oppenheimer',
    'Barbie',
    'John Wick: Chapter 4',
    'The Last of Us',
    'Spider-Man: Across the Spider-Verse',
    'Jawan'
  ],
  top10: [
    'The Dark Knight',
    'Inception',
    'Interstellar',
    'The Shawshank Redemption',
    'Parasite',
    'Avengers: Endgame',
    'Dune: Part Two',
    'RRR',
    'Breaking Bad',
    'The Godfather'
  ],
  trending: [
    'Oppenheimer',
    'Dune: Part Two',
    'The Dark Knight',
    'Spider-Man: No Way Home',
    'John Wick: Chapter 4',
    'RRR',
    'Spider-Man: Across the Spider-Verse',
    'Inside Out 2',
    'Shōgun'
  ],
  seasons: [
    'Breaking Bad',
    'Stranger Things',
    'Game of Thrones',
    'The Last of Us',
    'Squid Game',
    'Wednesday',
    'The Mandalorian',
    'The Boys',
    'Money Heist',
    'Dark',
    'The Witcher',
    'Succession',
    'The Bear',
    'Shōgun',
    'The Office',
    'Sherlock'
  ]
};
