export type CatalogKind = 'movie' | 'season' | 'parts';

export interface CatalogEntry {
  title: string;
  genre: string;
  narrator: string;
  posted: string;
  kind?: CatalogKind;
  count?: number;
  trending?: boolean;
}

export const CATALOG: CatalogEntry[] = [
  { title: 'Teach You a Lesson', genre: 'Drama', narrator: 'Rocky Kimomo', posted: '24 hours ago', kind: 'season' },
  { title: 'Evil Dead Burn', genre: 'Horror', narrator: 'Sankara Da Premier', posted: '2 days ago' },
  { title: 'Ready or Not 2: Here I Come', genre: 'Horror', narrator: 'Gaheza Simba', posted: '2 days ago' },
  { title: 'Send Help', genre: 'Horror', narrator: 'Gaheza Simba', posted: '2 days ago' },
  { title: 'From Paris with Love', genre: 'Action', narrator: 'Gaheza Simba', posted: '3 days ago' },
  { title: 'In the Grey', genre: 'Action', narrator: 'Gaheza Simba', posted: '4 days ago' },
  { title: 'The Maze Runner', genre: 'Action', narrator: 'Gaheza Simba', posted: '4 days ago' },
  { title: 'FILM ZASOHOTSE ICYUMWERU CYA 255.BIKOME KUGORANA.ABADOBANUZI BATO NABO BINYAYE MU ISUNZU MUGUPFUBURA', genre: 'Drama', narrator: 'Dj Danny Wamipango', posted: '4 days ago' },
  { title: 'Papillon', genre: 'Action', narrator: 'PK - The Sound', posted: '4 days ago', kind: 'parts', count: 2 },
  { title: 'READY OR NOT ROCKY', genre: 'Horror', narrator: 'Rocky Kimomo', posted: '2 years ago', trending: true },
  { title: "Death's Game", genre: 'Drama', narrator: 'Sankara Da Premier', posted: '2 weeks ago', kind: 'season', count: 5, trending: true },
  { title: 'A Shop for Killers', genre: 'Action', narrator: 'Rocky Kimomo', posted: '2 years ago', kind: 'season', count: 8, trending: true },
  { title: 'Agent Kim Reactivated', genre: 'Action', narrator: 'Rocky Kimomo', posted: 'last month', kind: 'season', count: 10, trending: true },
  { title: 'Nobody Rocky', genre: 'Action', narrator: 'Rocky Kimomo', posted: '11 months ago', kind: 'parts', count: 2, trending: true },
  { title: 'Obsession', genre: 'Romance', narrator: 'Sankara Da Premier', posted: '2 years ago', kind: 'season', count: 4, trending: true },
  { title: 'Face Off', genre: 'Action', narrator: 'Rocky Kimomo', posted: 'last month', trending: true },
  { title: 'Day Shift', genre: 'Action', narrator: 'Gaheza Simba', posted: 'last month', kind: 'parts', count: 2, trending: true },
  { title: 'Mortal Kombat II', genre: 'Action', narrator: 'Gaheza Simba', posted: 'last month', trending: true },
  { title: 'A Frozen Flower', genre: 'Drama', narrator: 'PK - The Sound', posted: 'last week', trending: true },
  { title: 'Saiyaara', genre: 'Indian', narrator: 'Rocky Kimomo', posted: 'last month', kind: 'parts', count: 2, trending: true },
  { title: 'Blast', genre: 'Indian', narrator: 'Rocky Kimomo', posted: 'last month', kind: 'parts', count: 2, trending: true },
  { title: 'Michael', genre: 'Drama', narrator: 'Rocky Kimomo', posted: 'last month', kind: 'parts', count: 2, trending: true },
  { title: 'I Will Find You Rocky', genre: 'Drama', narrator: 'Rocky Kimomo', posted: '2 months ago', kind: 'season', count: 8, trending: true },
  { title: 'My Country: The New Age', genre: 'Drama', narrator: 'Junior Giti', posted: '12 hours ago', kind: 'season' },
  { title: 'Smallville Season 2', genre: 'Action', narrator: 'Moses', posted: 'last week', kind: 'season', count: 4 },
  { title: 'All American', genre: 'Drama', narrator: 'Rocky Kimomo', posted: '2 weeks ago', kind: 'season', count: 8 },
  { title: 'The Oval Season 2', genre: 'Drama', narrator: 'Rocky Kimomo', posted: '2 weeks ago', kind: 'season', count: 7 },
  { title: 'The Girlfriend', genre: 'Romance', narrator: 'Sankara Da Premier', posted: '3 weeks ago', kind: 'season', count: 6 },
  { title: 'The Oval', genre: 'Drama', narrator: 'Rocky Kimomo', posted: '3 weeks ago', kind: 'season', count: 25 },
  { title: "Harper's Island", genre: 'Drama', narrator: 'Rocky Kimomo', posted: '3 weeks ago', kind: 'season', count: 11 },
  { title: "Let's Fight Ghost Bring It On, Ghost", genre: 'Drama', narrator: 'Rocky Kimomo', posted: '4 weeks ago', kind: 'season', count: 16 },
  { title: 'SIX Season 1', genre: 'Action', narrator: 'Junior Giti', posted: '4 weeks ago', kind: 'season', count: 8 },
  { title: 'Pinocchio', genre: 'Drama', narrator: 'Rocky Kimomo', posted: '4 weeks ago', kind: 'season', count: 20 },
  { title: 'Skin Trade', genre: 'Action', narrator: 'Sankara Da Premier', posted: 'last week', kind: 'parts', count: 2 },
  { title: 'The Wrath Of Vajra', genre: 'Action', narrator: 'Didier', posted: '2 weeks ago' },
  { title: 'Rise of the Legend', genre: 'Action', narrator: 'Sankara Da Premier', posted: '2 weeks ago' },
  { title: 'XXX: Return of Xander Cage', genre: 'Action', narrator: 'Gaheza Simba', posted: '2 weeks ago' },
  { title: 'Ninja Assassin', genre: 'Action', narrator: 'Yanga', posted: '3 weeks ago' },
  { title: 'Indemnity', genre: 'Action', narrator: 'Junior Giti', posted: '3 weeks ago' },
  { title: 'Ip Man 4: The Finale', genre: 'Action', narrator: 'Junior Giti', posted: '3 weeks ago' },
  { title: 'Addicted +18', genre: 'Romance', narrator: 'Sankara Da Premier', posted: 'last week' },
  { title: 'Bad Sister', genre: 'Romance', narrator: 'Sankara Da Premier', posted: '3 weeks ago' },
  { title: 'Fifty Shades of Grey', genre: 'Romance', narrator: 'PK - The Sound', posted: '3 weeks ago' },
  { title: 'The Polygamist Rocky Kimomo', genre: 'Romance', narrator: 'Rocky Kimomo', posted: '2 months ago', kind: 'season', count: 22 },
  { title: 'Office Romance', genre: 'Romance', narrator: 'Perfect', posted: '2 months ago' },
  { title: 'The Polygamist Junior Giti', genre: 'Romance', narrator: 'Junior Giti', posted: '2 months ago', kind: 'season', count: 22 },
  { title: 'Off Campus', genre: 'Romance', narrator: 'Perfect', posted: '2 months ago', kind: 'season', count: 8 },
  { title: 'Watching You', genre: 'Romance', narrator: 'Sankara Da Premier', posted: '3 months ago', kind: 'season', count: 6 },
  { title: 'The Best of Me', genre: 'Romance', narrator: 'PK - The Sound', posted: '5 months ago' },
  { title: 'Friend Request B . Rocky', genre: 'Romance', narrator: 'OSHAkur7', posted: '6 months ago' },
  { title: 'Friend Request . Rocky', genre: 'Romance', narrator: 'OSHAkur7', posted: '6 months ago' },
  { title: 'Daybreakers', genre: 'Horror', narrator: 'Sankara Da Premier', posted: '3 weeks ago' },
  { title: 'Deep Water', genre: 'Horror', narrator: 'Gaheza Simba', posted: 'last month' },
  { title: 'Apex', genre: 'Horror', narrator: 'Gaheza Simba', posted: '2 months ago' },
  { title: 'The Vampire Diaries S1 Ep22 Final', genre: 'Horror', narrator: 'Sankara Da Premier', posted: '2 months ago', kind: 'season', count: 22 },
  { title: 'They Will Kill You', genre: 'Horror', narrator: 'Sankara Da Premier', posted: '3 months ago' },
  { title: 'Fall', genre: 'Horror', narrator: 'Rocky Kimomo', posted: '3 months ago' },
  { title: '50 States of Fright Ep10 . Rocky', genre: 'Horror', narrator: 'OSHAkur7', posted: '3 months ago', kind: 'season' },
  { title: '50 States of Fright Ep9 . Rocky', genre: 'Horror', narrator: 'OSHAkur7', posted: '3 months ago', kind: 'season' },
  { title: '50 States of Fright Ep8 . Rocky', genre: 'Horror', narrator: 'OSHAkur7', posted: '3 months ago', kind: 'season' },
  { title: 'Raja Shivaji', genre: 'Indian', narrator: 'Perfect', posted: 'last month', kind: 'parts', count: 2 },
  { title: 'KD: The Devil', genre: 'Indian', narrator: 'Perfect', posted: '2 months ago', kind: 'parts', count: 2 },
  { title: 'Bhooth Bangla', genre: 'Indian', narrator: 'Perfect', posted: '2 months ago', kind: 'parts', count: 2 },
  { title: 'Biker', genre: 'Indian', narrator: 'Perfect', posted: '3 months ago' },
  { title: 'Ek Ajnabee', genre: 'Indian', narrator: 'Rocky Kimomo', posted: '3 months ago', kind: 'parts', count: 2 },
  { title: 'Dabangg 2', genre: 'Indian', narrator: 'Rocky Kimomo', posted: '3 months ago', kind: 'parts', count: 2 },
  { title: 'Kadamban', genre: 'Indian', narrator: 'Rocky Kimomo', posted: '3 months ago' },
  { title: 'Badass Ravikumar B . Perfect', genre: 'Indian', narrator: 'OSHAkur7', posted: '4 months ago' },
  { title: 'Badass Ravikumar . Perfect', genre: 'Indian', narrator: 'OSHAkur7', posted: '4 months ago' },
  { title: 'Every Child Is Special', genre: 'Indian', narrator: 'Mussa Savimbi', posted: '4 months ago' },
  { title: 'Kirikou and the Wild Beasts', genre: 'Cartoon', narrator: 'OSHAkur7', posted: '2 months ago' },
  { title: 'Peter Rabbit', genre: 'Cartoon', narrator: 'Junior Giti', posted: '2 months ago' },
  { title: 'Kirikou Part 1', genre: 'Cartoon', narrator: 'OSHAkur7', posted: '3 months ago' },
  { title: 'Bilal A New Breed of Hero', genre: 'Cartoon', narrator: 'Mussa Savimbi', posted: '3 months ago', kind: 'parts', count: 2 },
  { title: 'Coco . Master P', genre: 'Cartoon', narrator: 'OSHAkur7', posted: '3 months ago' },
  { title: 'Goat B . Master P', genre: 'Cartoon', narrator: 'OSHAkur7', posted: '4 months ago' },
  { title: 'Goat . Master P', genre: 'Cartoon', narrator: 'OSHAkur7', posted: '4 months ago' },
  { title: 'The Croods', genre: 'Cartoon', narrator: 'PK - The Sound', posted: '5 months ago' },
  { title: 'The Incredibles . Master P', genre: 'Cartoon', narrator: 'OSHAkur7', posted: '5 months ago' },
  { title: 'The Sea Beast . Master P', genre: 'Cartoon', narrator: 'OSHAkur7', posted: '5 months ago' },
  { title: 'Zootopia . Master P', genre: 'Cartoon', narrator: 'OSHAkur7', posted: '6 months ago' },
  { title: 'Luca . Master P', genre: 'Cartoon', narrator: 'OSHAkur7', posted: '6 months ago' },
  { title: 'Supergirl', genre: 'Sci-Fi', narrator: 'Perfect', posted: '6 days ago' },
  { title: 'Spider-Man: No Way Home', genre: 'Sci-Fi', narrator: 'Didier', posted: '2 weeks ago' },
  { title: 'Spider-Man: Far From Home', genre: 'Sci-Fi', narrator: 'Didier', posted: '2 weeks ago' },
  { title: 'Prey', genre: 'Sci-Fi', narrator: 'Rocky Kimomo', posted: '3 weeks ago' },
  { title: 'Avatar 3 Fire and Ash', genre: 'Sci-Fi', narrator: 'Perfect', posted: '4 months ago', kind: 'parts', count: 3 },
  { title: 'Troll 2 . Gaheza', genre: 'Sci-Fi', narrator: 'OSHAkur7', posted: '4 months ago' },
  { title: 'Mercy B . Habibu', genre: 'Sci-Fi', narrator: 'OSHAkur7', posted: '5 months ago' },
  { title: 'Mercy . Habibu', genre: 'Sci-Fi', narrator: 'OSHAkur7', posted: '5 months ago' },
  { title: 'Ant Man', genre: 'Sci-Fi', narrator: 'Sankara Da Premier', posted: '6 months ago' },
  { title: 'Anaconda . Gaheza', genre: 'Sci-Fi', narrator: 'OSHAkur7', posted: '6 months ago' },
  { title: 'Avatar 2 The Way of Water', genre: 'Sci-Fi', narrator: 'Gaheza Simba', posted: '7 months ago', kind: 'parts', count: 2 },
  { title: 'Predator Badlands . Gaheza SImba Agasobanuye Mu Kinyarwanda', genre: 'Sci-Fi', narrator: 'OSHAkur7', posted: '8 months ago' },
  { title: 'FILM ZASOTSE ICYUMWERU CYA 254. GAHINDA MURUHO WE! NGWINO URYAME NASHASHE. UMUDAYIMONI MURI', genre: 'Drama', narrator: 'Dj Danny Wamipango', posted: 'last week' },
  { title: 'FILM ZASOTSE MU GASOBANUYE ICYUMWERU CYA 253. KAGARARARA NIWE UTAHIWE .AGIYE KUBA NKA SAMUSONI.', genre: 'Drama', narrator: 'Dj Danny Wamipango', posted: '2 weeks ago' },
  { title: 'AGASOBANUYE ,FILM ZASOTSE ICYUMWERU CYA 252. ABASOBANUZI BARI KUGURISHA FILM ON LINE, USPC MURUKIKO', genre: 'Drama', narrator: 'Dj Danny Wamipango', posted: '3 weeks ago' },
  { title: 'Little Brother', genre: 'Comedy', narrator: 'Perfect', posted: 'last month' },
  { title: 'A Minecraft Movie - Gaheza Agasobanuye Mu Kinyarwanda', genre: 'Comedy', narrator: 'OSHAkur7', posted: '9 months ago' },
  { title: 'The Pickup B - Gaheza Agasobanuye Mu Kinyarwanda', genre: 'Comedy', narrator: 'OSHAkur7', posted: '10 months ago' },
  { title: 'The Pickup - Gaheza Agasobanuye Mu Kinyarwanda', genre: 'Comedy', narrator: 'OSHAkur7', posted: '10 months ago' },
  { title: 'Work It - Dylan Agasobanuye Mu Kinyarwanda', genre: 'Comedy', narrator: 'OSHAkur7', posted: 'last year' },
  { title: 'The Gods Must Be Crazy SAGATWA 2 - YANGA Agasobanuye Mu Kinyarwanda', genre: 'Comedy', narrator: 'OSHAkur7', posted: '2 years ago' },
  { title: 'The Gods Must Be Crazy SAGATWA 1 - YANGA Agasobanuye Mu Kinyarwanda', genre: 'Comedy', narrator: 'OSHAkur7', posted: '2 years ago' },
  { title: 'The Three Stooges C - junior giti Agasobanuye Mu Kinyarwanda', genre: 'Comedy', narrator: 'OSHAkur7', posted: '2 years ago' },
  { title: 'The Three Stooges B - junior giti Agasobanuye Mu Kinyarwanda', genre: 'Comedy', narrator: 'OSHAkur7', posted: '2 years ago' },
  { title: 'The Three Stooges - junior giti Agasobanuye Mu Kinyarwanda', genre: 'Comedy', narrator: 'OSHAkur7', posted: '2 years ago' },
  { title: 'MILK MONEY - SAVIMBI Agasobanuye Mu Kinyarwanda', genre: 'Comedy', narrator: 'OSHAkur7', posted: '2 years ago' },
  { title: 'Kindergarten Cop - Savimbi Agasobanuye Mu KInyarwanda', genre: 'Comedy', narrator: 'OSHAkur7', posted: '2 years ago' },
  { title: 'Films Zasohotse icyumweru cya 243', genre: 'Others', narrator: 'OSHAkur7', posted: '3 months ago' },
  { title: 'The Manipulated Ep9 . Junior Giti', genre: 'Others', narrator: 'OSHAkur7', posted: '5 months ago', kind: 'season' },
  { title: 'The Manipulated Ep8 . Junior Giti', genre: 'Others', narrator: 'OSHAkur7', posted: '5 months ago', kind: 'season' },
  { title: 'Films Zasohotse icyumweru cya 223', genre: 'Others', narrator: 'OSHAkur7', posted: '7 months ago' },
  { title: 'Films Zasohotse icyumweru cya 219', genre: 'Others', narrator: 'OSHAkur7', posted: '8 months ago' },
  { title: 'The Hidden Face .Sankra Agasobanuye Mu Kinyarwanda', genre: 'Others', narrator: 'OSHAkur7', posted: '9 months ago' },
  { title: 'ANIKULAPO 2B - SAVIMBI Agasobanuye Mu Kinyarwanda', genre: 'Others', narrator: 'OSHAkur7', posted: '9 months ago' },
  { title: 'ANIKULAPO 2A - SAVIMBI Agasobanuye Mu Kinyarwanda', genre: 'Others', narrator: 'OSHAkur7', posted: '9 months ago' },
  { title: 'Afterburn - Gaheza Agasobanuye mu Kinyarwanda', genre: 'Others', narrator: 'OSHAkur7', posted: '10 months ago' },
  { title: 'Messiah ep10 - Rocky Agasobanuye mu Kinyarwanda', genre: 'Others', narrator: 'OSHAkur7', posted: '10 months ago', kind: 'season' },
  { title: 'Messiah ep9 - Rocky Agasobanuye mu Kinyarwanda', genre: 'Others', narrator: 'OSHAkur7', posted: '10 months ago', kind: 'season' },
  { title: 'Messiah Ep8 - Rocky Agasobanuye mu Kinyarwanda', genre: 'Others', narrator: 'OSHAkur7', posted: '10 months ago', kind: 'season' }
];

export const ROW_TITLES: Record<string, string[]> = {
  recent: [
    'Teach You a Lesson',
    'Evil Dead Burn',
    'Ready or Not 2: Here I Come',
    'Send Help',
    'From Paris with Love',
    'In the Grey',
    'The Maze Runner',
    'FILM ZASOHOTSE ICYUMWERU CYA 255.BIKOME KUGORANA.ABADOBANUZI BATO NABO BINYAYE MU ISUNZU MUGUPFUBURA',
    'Papillon'
  ],
  top10: [
    'READY OR NOT ROCKY',
    "Death's Game",
    'A Shop for Killers',
    'Agent Kim Reactivated',
    'Nobody Rocky',
    'Obsession',
    'Face Off',
    'Day Shift',
    'Mortal Kombat II'
  ],
  trending: [
    'Teach You a Lesson',
    'A Frozen Flower',
    'Agent Kim Reactivated',
    "Death's Game",
    'Saiyaara',
    'Blast',
    'Michael',
    'I Will Find You Rocky'
  ],
  seasons: [
    'My Country: The New Age',
    'Teach You a Lesson',
    'Smallville Season 2',
    "Death's Game",
    'All American',
    'The Oval Season 2',
    'The Girlfriend',
    'The Oval',
    "Harper's Island",
    "Let's Fight Ghost Bring It On, Ghost",
    'SIX Season 1',
    'Pinocchio'
  ]
};

export const NARRATORS = [
  { name: 'OSHAkur7', count: 2768 },
  { name: 'Rocky Kimomo', count: 62 },
  { name: 'Sankara Da Premier', count: 30 },
  { name: 'Gaheza Simba', count: 24 },
  { name: 'PK - The Sound', count: 23 },
  { name: 'Junior Giti', count: 18 },
  { name: 'Perfect', count: 13 },
  { name: 'Skov', count: 12 },
  { name: 'Dj Danny Wamipango', count: 10 },
  { name: 'Yanga', count: 9 },
  { name: 'Mussa Savimbi', count: 9 },
  { name: 'B The Great', count: 3 }
];
